#!/usr/bin/python3

import os

target = os.environ['HOME'] + '/.local/bin'
if not os.path.isdir(target):
    os.system('mkdir ' + target)
os.system('ln -sf ' + os.getcwd() + '/main.py ' + target + '/ojsubmitter')
target = os.environ['HOME'] + '/.zsh_completions'
if not os.path.isdir(target):
    os.system('mkdir ' + target)
os.system('cp _ojsubmitter ' + target)
zcomp = """
fpath=($HOME/.zsh_completions $fpath)
autoload -U compinit
compinit"""
os.system("echo '{}' >> ~/.zshrc".format(zcomp))
print('Installation finished.')
